name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: install deps
      run: sudo apt-get update && sudo apt-get install -y wget git bash gcc gfortran g++ make file libopenmpi3 slurm libopenmpi-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

    - name: create singularity image
      run: sudo singularity build --notest matrixMul.sif matrixMul.def

