name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: install deps
      run: sudo apt update && sudo apt install -y wget git bash gcc gfortran g++ make file libopenmpi3 slurm libopenmpi-dev libfuse2 fuse2fs

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

    - name: experimenting
      run: wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce_4.1.3-focal_amd64.deb && sudo dpkg -i singularity-ce_4.1.3-focal_amd64.deb

    - name: create singularity image
      run: sudo singularity build --notest matrixMul.sif matrixMul.def

    - name: Upload Singularity Image via SCP
      uses: appleboy/scp-action@v1  
      with:
        host: ${{ secrets.USER_SECRET }}  
        key: ${{ secrets.PASSWORD_SECRET }}  
        port: 22  
        source: "../../matrixMul.sif"
        target: "./test"  

